import type { VitrineConfig, VitrinePublicData } from "@/types/vitrine";

export const DEFAULT_VITRINE_CONFIG: VitrineConfig = {
  id: "default",
  schoolDisplayName: "Etablissement",
  slogan: "",
  logoUrl: null,
  heroImageUrl: null,
  primaryColor: "#2563eb",
  secondaryColor: "#0f172a",
  accentColor: "#f59e0b",
  themeTemplate: "modern",
  contactPhone: null,
  contactEmail: null,
  contactAddress: null,
  facebookUrl: null,
  instagramUrl: null,
  whatsappNumber: null,
  metaDescription: null,
  heroBadgeLabel: null,
  heroBadgeValue: null,
  heroStat1Value: null,
  heroStat1Label: null,
  heroStat2Value: null,
  heroStat2Label: null,
  heroStat3Value: null,
  heroStat3Label: null,
  marqueeItem1: null,
  marqueeItem2: null,
  marqueeItem3: null,
  marqueeItem4: null,
  marqueeItem5: null,
  marqueeItem6: null,
  trustStat1Value: null,
  trustStat1Label: null,
  trustStat2Value: null,
  trustStat2Label: null,
  trustStat3Value: null,
  trustStat3Label: null,
  trustStat4Value: null,
  trustStat4Label: null,
  aboutEyebrow: null,
  aboutTitle: null,
  aboutTitleAccent: null,
  aboutDescription: null,
  aboutFeature1: null,
  aboutFeature2: null,
  aboutFeature3: null,
  aboutFeature4: null,
  aboutBadgeValue: null,
  aboutBadgeLabel: null,
  value1Title: null,
  value1Text: null,
  value2Title: null,
  value2Text: null,
  value3Title: null,
  value3Text: null,
  program1Title: null,
  program1Level: null,
  program1Text: null,
  program2Title: null,
  program2Level: null,
  program2Text: null,
  program3Title: null,
  program3Level: null,
  program3Text: null,
  testimonialQuote: null,
  testimonialAuthor: null,
  testimonialRole: null,
  ctaEyebrow: null,
  ctaTitle: null,
  ctaDescription: null,
  ctaPrimaryLabel: null,
  ctaPrimaryUrl: null,
  contactLatitude: null,
  contactLongitude: null,
  contactHours: null,
  published: false,
};

export function normalizeVitrineConfig(config?: VitrineConfig | null): VitrineConfig {
  const safeConfig = Object.fromEntries(
    Object.entries(config ?? {}).filter(([, value]) => value !== undefined)
  ) as Partial<VitrineConfig>;
  return { ...DEFAULT_VITRINE_CONFIG, ...safeConfig };
}

export function normalizeVitrinePublicData(data: VitrinePublicData): VitrinePublicData {
  return {
    ...data,
    config: normalizeVitrineConfig(data.config),
    pages: data.pages ?? [],
    announcements: data.announcements ?? [],
    gallery: data.gallery ?? [],
  };
}
